name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan 44.211.251.34 >> ~/.ssh/known_hosts

      - name: Pull and restart on EC2
        run: |
          ssh -i ~/.ssh/id_ed25519 ec2-user@44.211.251.34 "cd ~/hidden_rivers && git pull origin main && pm2 restart all" 